### PR TITLE
corrected import statement

### PR DESCRIPTION
**Pull request by oraac**
Modified import statement so it will run on my computer.

### CODE REVIEW

**Comment by stefanv** [comment]
This looks like the right fix to me

**Comment by oraac** [comment]
Wow.  You are super fast!  There is a similar issue with swt2.py, and maybe a few other demos.

**Comment by oraac** [comment]
Oh.  I see.  Every time I make a new commit it updates the pull request.  Pretty cool!

**Comment by stefanv** [comment]
Another thing that would be useful is if you modified the .travis.yml file to execute these scripts on each test run.

**Comment by oraac** [comment]
Good idea.  Wouldn't it more consistent to add these tests to the existing test framework?

**Comment by stefanv** [comment]
Yes, that's probably even better.  It may require a bit of lightweight refactoring of the scripts (e.g., into a "from script import main; main()"

**Comment by rgommers** [comment]
Thanks @oraac. I've pushed these changes as 496fab3a.

Second PR to run the demo script under ``pywt.test()`` would be great.

**Pull request closed without merging**
