### PR TITLE
BUG: fix _downcoef for level > 1

### PR DESCRIPTION
**Pull request by grlee77**
fixes issue #71 and adds a couple of tests

### CODE REVIEW

**Comment by rgommers** [comment]
LGTM, merged. Thanks @grlee77

**Comment by rgommers** [comment]
That Cython code is still quite hard to understand by the way, needs more cleaning up at some point.

**Comment by jiarongfu** [comment]
downcoef for level > 1 still doesn't seem to work because its output differs from the corresponding one in wavedec output by a lot. Can you look into this issue? Thanks.

**Comment by grlee77** [comment]
Hi @jiarongfu.  I will take a look.   We are actively increasing the test coverage, so reports like this are very helpful.  It seems from the example below that the ``downcoef`` result matches for the approximation coefficients, but not for the detail coefficients.  Is this what you have observed?

```python
import pywt
import numpy as np
from numpy.testing import assert_array_almost_equal
r = np.random.randn(16)
a2, d2, d1 = pywt.wavedec(r, 'haar', level=2)

assert_array_almost_equal(a2, pywt.downcoef('a', r, wavelet='haar', level=2))
assert_array_almost_equal(d2, pywt.downcoef('d', r, wavelet='haar', level=2))
```
The second ``assert_array_almost_equal`` call above fails, but the first passes

**Comment by jiarongfu** [comment]
@grlee77 I believe that's right, though I didn't check for approximation coefficients on each level.

**Pull request merged**
